---
owner: stratumfarm
repo: upptime

sites:
  - name: Whalesburg
    url: https://whalesburg.com

assignees:
  - jon4hz
  - ei8ht187

status-website:
  cname: status.whalesburg.com
  name: Status
  introTitle: Whalesburg Status Page
  introMessage: Welcome to our status page
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://whalesburg.com
    - title: GitHub
      href: https://github.com/whalesburg
  theme: night
  logoUrl: https://raw.githubusercontent.com/stratumfarm/upptime/master/assets/wb_icon.svg
  favicon: https://raw.githubusercontent.com/stratumfarm/upptime/master/assets/favicon-32x32.png
  faviconSvg: https://raw.githubusercontent.com/stratumfarm/upptime/master/assets/wb_icon.svg
  robotsText: "User-agent: * \n Disallow: /"
  
